### ISSUE TITLE
Random crash : Zlib._binding.onerror (zlib.js:295:17)

### ISSUE THREAD

**Issue by kripskroll** [JCB9090/juan-carlos-torrents-2#7]
Here is a random crach that happens after few minutes

We have 172 torrents, 84 queued

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: invalid literal/length code
    at Zlib._binding.onerror (zlib.js:295:17)

**Comment by JCB9090** [comment]
I'm getting something else after a few minutes

```
Error: read ECONNRESET
    at exports._errnoException (util.js:746:11)
    at TCP.onread (net.js:561:26)
```

this is weird
i'll investigate, seems like an issue in multipass

**Comment by JCB9090** [comment]
btw @kripskroll can you update to the latest multipass (i've bumped it in package.json) and see if this happens?

**Comment by kripskroll** [comment]
I did it and it seems to work for now.
I will let you know
Thanks
